In [125]:
import pandas as pd
import numpy as np
from numpy.linalg import inv

In [126]:
# Answer 1
np.__version__

'1.19.5'

In [127]:
# Answer 2
pd.__version__

'1.3.3'

In [128]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv")
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [150]:
# Answer 3
bmw_avg = df[df["Make"] == "BMW"]["MSRP"].mean().round(2)
bmw_avg

61546.76

In [132]:
fifteen_or_after_df = df[df["Year"] >= 2015]
fifteen_or_after_df.head()

Make       Model  Year                Engine Fuel Type  Engine HP  \
32  FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
33  FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
34  FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
41   BMW    2 Series  2016     premium unleaded (required)      240.0   
42   BMW    2 Series  2016     premium unleaded (required)      240.0   

    Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
32               4.0            MANUAL  rear wheel drive              2.0   
33               4.0            MANUAL  rear wheel drive              2.0   
34               4.0            MANUAL  rear wheel drive              2.0   
41               4.0         AUTOMATIC  rear wheel drive              2.0   
42               4.0         AUTOMATIC  rear wheel drive              2.0   

       Market Category Vehicle Size Vehicle Style  highway MPG  city mpg  \
32         Performance      Compact   Convertible           35        26   
33         Performance      Compact   Convertible           35        26   
34         Performance      Compact   Convertible           35        26   
41  Luxury,Performance      Compact         Coupe           35        23   
42              Luxury      Compact   Convertible           34        23   

    Popularity   MSRP  
32         819  27495  
33         819  24995  
34         819  28195  
41        3916  32850  
42        3916  38650

In [133]:
# Answer 4
fifteen_or_after_df["Engine HP"].isnull().sum()

51

In [134]:
hp_before_avg = fifteen_or_after_df["Engine HP"].mean()
hp_before_avg

272.98771870794076

In [135]:
fifteen_or_after_df = fifteen_or_after_df.fillna(value={"Engine HP": hp_before_avg})
fifteen_or_after_df.head()

Make       Model  Year                Engine Fuel Type  Engine HP  \
32  FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
33  FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
34  FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
41   BMW    2 Series  2016     premium unleaded (required)      240.0   
42   BMW    2 Series  2016     premium unleaded (required)      240.0   

    Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
32               4.0            MANUAL  rear wheel drive              2.0   
33               4.0            MANUAL  rear wheel drive              2.0   
34               4.0            MANUAL  rear wheel drive              2.0   
41               4.0         AUTOMATIC  rear wheel drive              2.0   
42               4.0         AUTOMATIC  rear wheel drive              2.0   

       Market Category Vehicle Size Vehicle Style  highway MPG  city mpg  \
32         Performance      Compact   Convertible           35        26   
33         Performance      Compact   Convertible           35        26   
34         Performance      Compact   Convertible           35        26   
41  Luxury,Performance      Compact         Coupe           35        23   
42              Luxury      Compact   Convertible           34        23   

    Popularity   MSRP  
32         819  27495  
33         819  24995  
34         819  28195  
41        3916  32850  
42        3916  38650

In [136]:
# Check my work
fifteen_or_after_df["Engine HP"].isnull().sum()

0

In [137]:
hp_after_avg = fifteen_or_after_df["Engine HP"].mean()
hp_after_avg

272.98771870794076

In [138]:
# Answer 5 - No Change
print(round(hp_before_avg))
print(round(hp_after_avg))

273
273


In [139]:
rolls_royce_df = df[df["Make"] == "Rolls-Royce"]
rolls_royce_df.head()

Make            Model  Year             Engine Fuel Type  \
2921  Rolls-Royce         Corniche  2001  premium unleaded (required)   
3505  Rolls-Royce             Dawn  2016  premium unleaded (required)   
5275  Rolls-Royce  Ghost Series II  2015  premium unleaded (required)   
5276  Rolls-Royce  Ghost Series II  2015  premium unleaded (required)   
5277  Rolls-Royce  Ghost Series II  2016  premium unleaded (required)   

      Engine HP  Engine Cylinders Transmission Type     Driven_Wheels  \
2921      325.0               8.0         AUTOMATIC  rear wheel drive   
3505      563.0              12.0         AUTOMATIC  rear wheel drive   
5275      563.0              12.0         AUTOMATIC  rear wheel drive   
5276      563.0              12.0         AUTOMATIC  rear wheel drive   
5277      563.0              12.0         AUTOMATIC  rear wheel drive   

      Number of Doors                 Market Category Vehicle Size  \
2921              2.0                   Exotic,Luxury        Large   
3505              2.0  Exotic,Luxury,High-Performance        Large   
5275              4.0       Exotic,Luxury,Performance        Large   
5276              4.0       Exotic,Luxury,Performance        Large   
5277              4.0       Exotic,Luxury,Performance        Large   

     Vehicle Style  highway MPG  city mpg  Popularity    MSRP  
2921   Convertible           15        10          86  359990  
3505   Convertible           19        12          86  335000  
5275         Sedan           21        13          86  286750  
5276         Sedan           21        13          86  319400  
5277         Sedan           21        13          86  295850

In [140]:
rolls_royce_df = rolls_royce_df[["Engine HP", "Engine Cylinders", "highway MPG"]]
rolls_royce_df.head()

Engine HP  Engine Cylinders  highway MPG
2921      325.0               8.0           15
3505      563.0              12.0           19
5275      563.0              12.0           21
5276      563.0              12.0           21
5277      563.0              12.0           21

In [141]:
# Per the homework, should only be 7 rows
rolls_royce_df = rolls_royce_df.drop_duplicates()
rolls_royce_df

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [142]:
X = rolls_royce_df.values
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [143]:
X_t = X.T
X_t

array([[325., 563., 563., 563., 322., 453., 624.],
       [  8.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 15.,  19.,  21.,  20.,  15.,  19.,  21.]])

In [144]:
XTX = X_t.dot(X)
XTX_inv = inv(XTX)
XTX_inv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [145]:
# Answer 6
XTX_inv.sum()

0.032212320677486125

In [146]:
y = [1000, 1100, 900, 1200, 1000, 850, 1300]
y

[1000, 1100, 900, 1200, 1000, 850, 1300]

In [147]:
X_t_times_XTX_inv = XTX_inv.dot(X.T)
X_t_times_XTX_inv

array([[-0.00486592,  0.00336507, -0.00049461,  0.00143523, -0.00139492,
        -0.0023309 ,  0.00266407],
       [-0.19020088,  0.09362543, -0.08379139,  0.00491702,  0.22997159,
        -0.00609915, -0.02848958],
       [ 0.25164625, -0.13888652,  0.0729151 , -0.03298571, -0.09739786,
         0.07339609, -0.04480526]])

In [151]:
# Answer 7
w = X_t_times_XTX_inv.dot(y)
w[0]

0.19989598183188972